// Annual analytics with actionable insights. Chart.js is loaded only when this page opens.
let chartJsPromise=null;
function ensureChartJs(){
  if(window.Chart)return Promise.resolve(window.Chart);
  if(chartJsPromise)return chartJsPromise;
  chartJsPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js';s.async=true;s.onload=()=>window.Chart?resolve(window.Chart):reject(new Error('Chart.js не инициализирован'));s.onerror=()=>reject(new Error('Не удалось загрузить графики'));document.head.appendChild(s)}).finally(()=>{if(!window.Chart)chartJsPromise=null});
  return chartJsPromise;
}

function yearTx(year=+state.year){return state.transactions.filter(x=>new Date(x.occurred_at).getFullYear()===+year)}
function yearSeries(year=+state.year){const income=Array(12).fill(0),expense=Array(12).fill(0),count=Array(12).fill(0);yearTx(year).forEach(x=>{const m=new Date(x.occurred_at).getMonth();(x.type==='income'?income:expense)[m]+=Number(x.amount||0);count[m]++});const balance=income.map((v,i)=>v-expense[i]);let running=0;const cumulative=balance.map(v=>(running+=v));return{income,expense,balance,cumulative,count}}
function yearSummary(year=+state.year){
  const tx=yearTx(year),income=tx.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount||0),0),expense=tx.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount||0),0),balance=income-expense,saved=income?Math.round(balance/income*100):0,series=yearSeries(year),now=new Date(),months=year===now.getFullYear()?Math.max(1,now.getMonth()+1):12,avgExpense=expense/months,avgIncome=income/months;
  const bestIndex=series.balance.reduce((best,v,i)=>v>series.balance[best]?i:best,0),worstIndex=series.balance.reduce((worst,v,i)=>v<series.balance[worst]?i:worst,0),categorySums={};tx.filter(x=>x.type==='expense').forEach(x=>categorySums[x.category_id]=(categorySums[x.category_id]||0)+Number(x.amount||0));const categories=Object.entries(categorySums).sort((a,b)=>b[1]-a[1]),largestExpense=tx.filter(x=>x.type==='expense').sort((a,b)=>Number(b.amount)-Number(a.amount))[0]||null;
  return{year,tx,income,expense,balance,saved,avgExpense,avgIncome,series,bestIndex,worstIndex,categories,largestExpense,months};
}
function yearPersonStats(personId,year=+state.year){const tx=yearTx(year).filter(x=>x.person_id===personId),income=tx.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount||0),0),expense=tx.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount||0),0);return{income,expense,balance:income-expense}}
function percentDelta(current,previous){if(!previous)return current?null:0;return Math.round((current-previous)/Math.abs(previous)*100)}
function deltaText(value){if(value==null)return'нет базы сравнения';if(value===0)return'без изменений';return `${value>0?'+':''}${value}% к прошлому году`}

function yearlyExpenseList(categories,total){if(!categories.length)return `<div class="empty">Расходов за ${state.year} год пока нет</div>`;const max=categories[0][1]||1;return categories.slice(0,7).map(([id,val],i)=>`<div class="annual-category"><span class="annual-rank">${i+1}</span><div class="annual-category-main"><div><b>${esc(catName(id))}</b><span>${money(val)} · ${total?Math.round(val/total*100):0}%</span></div><div class="bar-track"><div class="bar" style="width:${Math.max(3,val/max*100)}%"></div></div></div></div>`).join('')}

function analyticsInsights(y,prev){
  const top=y.categories[0],topShare=top&&y.expense?Math.round(top[1]/y.expense*100):0,expenseDelta=percentDelta(y.expense,prev.expense),incomeDelta=percentDelta(y.income,prev.income),rateText=y.saved>=20?'Сбережения на хорошем уровне':y.saved>=10?'Есть запас для накоплений':y.saved>=0?'Расходы почти равны доходам':'Расходы выше доходов',rateClass=y.saved>=10?'positive':y.saved<0?'negative':'warning-text';
  return `<div class="analytics-insights"><div class="analytics-insight"><span>Доля сбережений</span><b class="${rateClass}">${y.saved}%</b><small>${rateText}</small></div><div class="analytics-insight"><span>Доходы</span><b>${money(y.avgIncome)} / мес.</b><small>${deltaText(incomeDelta)}</small></div><div class="analytics-insight"><span>Расходы</span><b>${money(y.avgExpense)} / мес.</b><small>${deltaText(expenseDelta)}</small></div><div class="analytics-insight"><span>Главная статья</span><b>${top?esc(catName(top[0])):'—'}</b><small>${top?`${topShare}% всех расходов`:''}</small></div>${y.largestExpense?`<div class="analytics-insight"><span>Крупнейшая покупка</span><b>${money(y.largestExpense.amount)}</b><small>${esc(catName(y.largestExpense.category_id))} · ${new Date(y.largestExpense.occurred_at).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})}</small></div>`:''}<div class="analytics-insight"><span>Лучший / слабый месяц</span><b>${MONTHS[y.bestIndex]} / ${MONTHS[y.worstIndex]}</b><small>${money(y.series.balance[y.bestIndex])} / ${money(y.series.balance[y.worstIndex])}</small></div></div>`;
}

function analyticsPage(){
  const y=yearSummary(+state.year),prev=yearSummary(+state.year-1),topCategory=y.categories[0];
  return `<div class="page-head"><div><h2 class="page-title">Аналитика ${state.year}</h2><div class="page-subtitle">Не только графики: ключевые выводы о доходах, расходах и накоплениях семьи.</div></div></div>
  <section class="grid kpis annual-kpis"><div class="card"><div class="kpi-label">Доходы за год</div><div class="kpi-value positive">${money(y.income)}</div><small>${deltaText(percentDelta(y.income,prev.income))}</small></div><div class="card"><div class="kpi-label">Расходы за год</div><div class="kpi-value negative">${money(y.expense)}</div><small>${deltaText(percentDelta(y.expense,prev.expense))}</small></div><div class="card"><div class="kpi-label">Финансовый результат</div><div class="kpi-value ${y.balance>=0?'positive':'negative'}">${money(y.balance)}</div></div><div class="card"><div class="kpi-label">Доля сбережений</div><div class="kpi-value ${y.saved>=0?'positive':'negative'}">${y.saved}%</div></div></section>
  ${analyticsInsights(y,prev)}
  <section class="annual-facts"><div class="annual-fact"><span>Операций</span><b>${y.tx.length}</b></div><div class="annual-fact"><span>Средний расход / месяц</span><b>${money(y.avgExpense)}</b></div><div class="annual-fact"><span>Лучший месяц</span><b>${MONTHS[y.bestIndex]}</b><small class="${y.series.balance[y.bestIndex]>=0?'positive':'negative'}">${money(y.series.balance[y.bestIndex])}</small></div><div class="annual-fact"><span>Крупнейшая статья расходов</span><b>${topCategory?esc(catName(topCategory[0])):'—'}</b><small>${topCategory?money(topCategory[1]):''}</small></div></section>
  <div class="grid analytics-grid annual-analytics-grid"><div class="card annual-wide"><h3>Доходы и расходы по месяцам</h3><div class="chart-box"><canvas id="yearChart"></canvas></div></div><div class="card"><h3>Накопленный результат</h3><div class="chart-box small"><canvas id="balanceChart"></canvas></div></div><div class="card"><h3>Расходы за год по категориям</h3><div class="chart-box small"><canvas id="categoryChart"></canvas></div></div><div class="card"><h3>Муж и жена за год</h3><div class="chart-box small"><canvas id="peopleChart"></canvas></div></div><div class="card"><h3>Куда ушло больше всего</h3>${yearlyExpenseList(y.categories,y.expense)}</div></div>`;
}

function destroyCharts(){state.charts.forEach(c=>{try{c.destroy()}catch(_){}});state.charts=[]}
function drawAnalytics(){
  const ChartLib=window.Chart;if(!ChartLib)return;ChartLib.defaults.color='#cbb994';ChartLib.defaults.borderColor='rgba(177,139,82,.20)';const y=yearSummary(),series=y.series,common={responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#d8c6a5'}}}};
  const yearEl=document.getElementById('yearChart');if(yearEl)state.charts.push(new ChartLib(yearEl,{type:'line',data:{labels:MONTHS,datasets:[{label:'Доходы',data:series.income,borderColor:'#67d29d',backgroundColor:'rgba(103,210,157,.14)',tension:.35,fill:true},{label:'Расходы',data:series.expense,borderColor:'#ff766f',backgroundColor:'rgba(255,118,111,.10)',tension:.35,fill:true}]},options:common}));
  const balanceEl=document.getElementById('balanceChart');if(balanceEl)state.charts.push(new ChartLib(balanceEl,{type:'line',data:{labels:MONTHS,datasets:[{label:'Накопленный баланс',data:series.cumulative,borderColor:'#d6ad62',backgroundColor:'rgba(214,173,98,.12)',tension:.3,fill:true}]},options:common}));
  const top=y.categories.slice(0,8),catEl=document.getElementById('categoryChart');if(catEl)state.charts.push(new ChartLib(catEl,{type:'doughnut',data:{labels:top.map(x=>catName(x[0])),datasets:[{data:top.map(x=>x[1]),backgroundColor:['#d6ad62','#8ca6b7','#9b7250','#6f8c79','#b58f5d','#7b6b8e','#a45f55','#638a91']}]},options:{...common,plugins:{legend:{position:'bottom',labels:{color:'#d8c6a5'}}}}}));
  const ps=state.people.map(p=>yearPersonStats(p.id)),peopleEl=document.getElementById('peopleChart');if(peopleEl)state.charts.push(new ChartLib(peopleEl,{type:'bar',data:{labels:state.people.map(p=>p.display_name),datasets:[{label:'Доход',data:ps.map(x=>x.income),backgroundColor:'#67d29d'},{label:'Расход',data:ps.map(x=>x.expense),backgroundColor:'#ff766f'}]},options:common}));
}
