// Financial goals and savings.
function goalSaved(goalId){return state.goalContributions.filter(x=>x.goal_id===goalId).reduce((sum,x)=>sum+Number(x.amount),0)}
function goalProgress(goal){const saved=goalSaved(goal.id),target=Number(goal.target_amount)||0;return{saved,target,remaining:Math.max(0,target-saved),pct:target?Math.max(0,Math.min(100,Math.round(saved/target*100))):0}}
function goalDateText(goal){if(!goal.target_date)return'Без срока';const d=new Date(`${goal.target_date}T12:00:00`);return d.toLocaleDateString('ru-RU',{day:'2-digit',month:'short',year:'numeric'})}

function goalsPage(){
  const active=state.goals.filter(g=>!g.archived),archived=state.goals.filter(g=>g.archived);
  const totalTarget=active.reduce((s,g)=>s+Number(g.target_amount||0),0),totalSaved=active.reduce((s,g)=>s+goalSaved(g.id),0);
  return `<div class="page-head"><div><h2 class="page-title">Финансовые цели</h2><div class="page-subtitle">Копите на важные покупки и семейные планы отдельно от текущих расходов.</div></div></div>
  <section class="grid goal-kpis"><div class="card"><div class="kpi-label">Активных целей</div><div class="kpi-value">${active.length}</div></div><div class="card"><div class="kpi-label">Целевая сумма</div><div class="kpi-value">${money(totalTarget)}</div></div><div class="card"><div class="kpi-label">Накоплено</div><div class="kpi-value positive">${money(totalSaved)}</div></div><div class="card"><div class="kpi-label">Осталось</div><div class="kpi-value">${money(Math.max(0,totalTarget-totalSaved))}</div></div></section>
  <div class="goal-layout"><div class="card"><h3>Новая цель</h3><div id="goalNotice"></div><form id="goalForm" class="quick-form"><div class="field full"><label>Название</label><input id="goalName" required placeholder="Например: Отпуск"></div><div class="field"><label>Сумма, ₸</label><input id="goalTarget" type="number" min="1" step="1" required></div><div class="field"><label>Срок</label><input id="goalDate" type="date"></div><div class="field full"><label>Комментарий</label><input id="goalNote" placeholder="Необязательно"></div><div class="full"><button class="btn btn-primary btn-wide">Создать цель</button></div></form></div><div class="goals-list">${active.length?active.map(goalCard).join(''):'<div class="card empty">Финансовых целей пока нет</div>'}</div></div>
  ${archived.length?`<div class="card archived-goals"><h3>Архив</h3>${archived.map(goalCard).join('')}</div>`:''}`
}

function goalCard(g){const p=goalProgress(g);const recent=state.goalContributions.filter(x=>x.goal_id===g.id).slice(0,4);return `<div class="card goal-card ${g.archived?'archived':''}"><div class="goal-head"><div><h3>${esc(g.name)}</h3><div class="muted">${goalDateText(g)}${g.note?` · ${esc(g.note)}`:''}</div></div><b>${money(p.target)}</b></div><div class="goal-progress"><div class="goal-progress-fill" style="width:${p.pct}%"></div></div><div class="goal-stats"><span>Накоплено <b class="positive">${money(p.saved)}</b></span><span>Осталось <b>${money(p.remaining)}</b></span><span><b>${p.pct}%</b></span></div>${!g.archived?`<form class="goal-contribution-form" data-goal="${g.id}"><input class="goal-amount" type="number" step="1" placeholder="Сумма" required><input class="goal-note" placeholder="Комментарий"><button class="btn btn-soft btn-small" type="submit">Пополнить</button></form>`:''}<div class="goal-history">${recent.length?recent.map(x=>`<div><span>${new Date(x.contributed_at).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})}${x.note?` · ${esc(x.note)}`:''}</span><b class="${Number(x.amount)>=0?'positive':'negative'}">${Number(x.amount)>=0?'+':''}${money(x.amount)}</b></div>`).join(''):'<div class="muted">Пополнений пока нет</div>'}</div><div class="goal-actions">${!g.archived?`<button class="btn btn-soft btn-small goalWithdraw" data-id="${g.id}">Уменьшить</button><button class="btn btn-soft btn-small goalArchive" data-id="${g.id}">В архив</button>`:`<button class="btn btn-soft btn-small goalRestore" data-id="${g.id}">Вернуть</button>`}<button class="icon-btn goalDelete" data-id="${g.id}" title="Удалить цель">×</button></div></div>`}

function bindGoals(){
  const form=document.getElementById('goalForm');if(form)form.onsubmit=async e=>{e.preventDefault();const payload={family_id:state.family.id,name:document.getElementById('goalName').value.trim(),target_amount:Number(document.getElementById('goalTarget').value),target_date:document.getElementById('goalDate').value||null,note:document.getElementById('goalNote').value.trim()||null,created_by:state.user.id};const {error}=await sb.from('financial_goals').insert(payload);if(error)return notice('goalNotice',error.message);await loadData()};
  document.querySelectorAll('.goal-contribution-form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const amount=Number(f.querySelector('.goal-amount').value),note=f.querySelector('.goal-note').value.trim()||null;if(!amount)return;const {error}=await sb.from('goal_contributions').insert({goal_id:f.dataset.goal,family_id:state.family.id,amount,note,created_by:state.user.id});if(error)return alert(error.message);await loadData()});
  document.querySelectorAll('.goalWithdraw').forEach(b=>b.onclick=async()=>{const value=Number(prompt('На сколько уменьшить накопленную сумму?','0'));if(!value||value<0)return;const {error}=await sb.from('goal_contributions').insert({goal_id:b.dataset.id,family_id:state.family.id,amount:-value,note:'Уменьшение накоплений',created_by:state.user.id});if(error)return alert(error.message);await loadData()});
  document.querySelectorAll('.goalArchive').forEach(b=>b.onclick=async()=>{const {error}=await sb.from('financial_goals').update({archived:true,updated_at:new Date().toISOString()}).eq('id',b.dataset.id);if(error)return alert(error.message);await loadData()});
  document.querySelectorAll('.goalRestore').forEach(b=>b.onclick=async()=>{const {error}=await sb.from('financial_goals').update({archived:false,updated_at:new Date().toISOString()}).eq('id',b.dataset.id);if(error)return alert(error.message);await loadData()});
  document.querySelectorAll('.goalDelete').forEach(b=>b.onclick=async()=>{if(!confirm('Удалить цель и всю историю её пополнений?'))return;const {error}=await sb.from('financial_goals').delete().eq('id',b.dataset.id);if(error)return alert(error.message);await loadData()})
}
