// Financial goals and savings. Goal funding is linked atomically to accounting operations.
function goalSaved(goalId){return state.goalContributions.filter(x=>x.goal_id===goalId).reduce((sum,x)=>sum+Number(x.amount),0)}
function goalProgress(goal){const saved=goalSaved(goal.id),target=Number(goal.target_amount)||0;return{saved,target,remaining:Math.max(0,target-saved),pct:target?Math.max(0,Math.min(100,Math.round(saved/target*100))):0}}
function goalDateText(goal){if(!goal.target_date)return'Без срока';const d=new Date(`${goal.target_date}T12:00:00`);return d.toLocaleDateString('ru-RU',{day:'2-digit',month:'short',year:'numeric'})}
function parseGoalAmount(value){const normalized=String(value??'').replace(/[\s\u00a0\u202f]/g,'').replace(',','.').replace(/[^0-9.+-]/g,'');const amount=Number(normalized);return Number.isFinite(amount)?amount:0}
function goalContributionStatus(form,message,type=''){const box=form?.querySelector('.goal-contribution-notice');if(!box)return;box.textContent=message||'';box.className=`goal-contribution-notice ${type}`.trim()}
function currentGoalContributor(){return state.people.find(x=>x.linked_user_id===state.user?.id)||null}
function goalContributorName(contribution){return byId(state.people,contribution.person_id)?.display_name||state.people.find(x=>x.linked_user_id===contribution.created_by)?.display_name||'Участник'}
function goalContributionDateTime(value){const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function goalHistoryRow(x){const positive=Number(x.amount)>=0,action=positive?'Внесено':'Возвращено';return `<div class="goal-history-row"><span><b>${esc(goalContributorName(x))}</b> · ${goalContributionDateTime(x.contributed_at)}<small>${action}${x.note?` · ${esc(x.note)}`:''}${x._offline?' · ожидает синхронизации':''}</small></span><b class="${positive?'positive':'negative'}">${positive?'+':''}${money(x.amount)}</b></div>`}
function goalsPage(){const active=state.goals.filter(g=>!g.archived),archived=state.goals.filter(g=>g.archived),totalTarget=active.reduce((s,g)=>s+Number(g.target_amount||0),0),totalSaved=active.reduce((s,g)=>s+goalSaved(g.id),0);return `<div class="page-head"><div><h2 class="page-title">Финансовые цели</h2><div class="page-subtitle">Пополнение цели автоматически становится расходом того, кто вошёл в приложение, и учитывается в общем балансе.</div></div></div><section class="grid goal-kpis"><div class="card"><div class="kpi-label">Активных целей</div><div class="kpi-value">${active.length}</div></div><div class="card"><div class="kpi-label">Целевая сумма</div><div class="kpi-value">${money(totalTarget)}</div></div><div class="card"><div class="kpi-label">Накоплено</div><div class="kpi-value positive">${money(totalSaved)}</div></div><div class="card"><div class="kpi-label">Осталось</div><div class="kpi-value">${money(Math.max(0,totalTarget-totalSaved))}</div></div></section><div class="goal-layout"><div class="card"><h3>Новая цель</h3><div id="goalNotice"></div><form id="goalForm" class="quick-form"><div class="field full"><label>Название</label><input id="goalName" required placeholder="Например: Отпуск"></div><div class="field"><label>Сумма, ₸</label><input id="goalTarget" type="number" min="1" step="1" required></div><div class="field"><label>Срок</label><input id="goalDate" type="date"></div><div class="field full"><label>Комментарий</label><input id="goalNote" placeholder="Необязательно"></div><div class="full"><button class="btn btn-primary btn-wide">Создать цель</button></div></form></div><div class="goals-list">${active.length?active.map(goalCard).join(''):'<div class="card empty">Финансовых целей пока нет</div>'}</div></div>${archived.length?`<div class="card archived-goals"><h3>Архив</h3>${archived.map(goalCard).join('')}</div>`:''}`}
function goalCard(g){const p=goalProgress(g),recent=state.goalContributions.filter(x=>x.goal_id===g.id).slice(0,6),contributor=currentGoalContributor();return `<div class="card goal-card ${g.archived?'archived':''}"><div class="goal-head"><div><h3>${esc(g.name)}${g._offline?'<span class="offline-row-badge">Ожидает синхронизации</span>':''}</h3><div class="muted">${goalDateText(g)}${g.note?` · ${esc(g.note)}`:''}</div></div><b>${money(p.target)}</b></div><div class="goal-progress"><div class="goal-progress-fill" style="width:${p.pct}%"></div></div><div class="goal-stats"><span>Накоплено <b class="positive">${money(p.saved)}</b></span><span>Осталось <b>${money(p.remaining)}</b></span><span><b>${p.pct}%</b></span></div>${!g.archived?`<form class="goal-contribution-form" data-goal="${g.id}" novalidate><div class="goal-accounting-note">${contributor?`Внесёт <b>${esc(contributor.display_name)}</b> · операция попадёт в расходы «Цели и накопления»`:'Аккаунт не привязан к Мужу или Жене — пополнение будет недоступно'}</div><input class="goal-amount" type="text" inputmode="decimal" autocomplete="off" placeholder="Сумма, ₸" aria-label="Сумма пополнения"><input class="goal-note" placeholder="Комментарий" aria-label="Комментарий к пополнению"><button class="btn btn-soft btn-small goal-contribute-btn" type="submit" ${contributor?'':'disabled'}>Пополнить</button><div class="goal-contribution-notice" aria-live="polite"></div></form>`:''}<div class="goal-history">${recent.length?recent.map(goalHistoryRow).join(''):'<div class="muted">Пополнений пока нет</div>'}</div><div class="goal-actions">${!g.archived?`<button class="btn btn-soft btn-small goalWithdraw" data-id="${g.id}" ${contributor?'':'disabled'}>Уменьшить</button><button class="btn btn-soft btn-small goalArchive" data-id="${g.id}">В архив</button>`:`<button class="btn btn-soft btn-small goalRestore" data-id="${g.id}">Вернуть</button>`}<button class="btn btn-danger btn-small goalDelete" data-id="${g.id}">Удалить</button></div></div>`}
async function saveGoalEntity(entity,id,payload){if(window.FinanceOffline?.saveEntity)return window.FinanceOffline.saveEntity(entity,{id:id||null,payload});const table=entity==='goal'?'financial_goals':'goal_contributions';if(id)return sb.from(table).update(payload).eq('id',id).select().single();return sb.from(table).insert(payload).select().single()}
async function saveLinkedGoalContribution(goalId,amount,note){
  if(!navigator.onLine)return{data:null,error:new Error('Для пополнения цели нужен интернет: сумма одновременно записывается в цель и в операции, чтобы баланс не расходился.')};
  try{
    const result=await sb.rpc('contribute_to_goal',{p_goal_id:goalId,p_amount:amount,p_note:note||null});
    if(result.error)return{data:null,error:result.error};
    const payload=result.data||{},contribution=payload.contribution||null,transaction=payload.transaction||null;
    if(transaction)syncTransactionState(transaction);
    if(contribution){upsertById(state.goalContributions,contribution);state.goalContributions.sort((a,b)=>new Date(b.contributed_at)-new Date(a.contributed_at))}
    window.FinanceOffline?.persistSnapshotSoon?.();
    return{data:contribution,transaction,error:null};
  }catch(error){return{data:null,error}}
}
async function submitGoalContribution(form){
  if(!form||form.dataset.saving==='1')return;
  const amountInput=form.querySelector('.goal-amount'),noteInput=form.querySelector('.goal-note'),button=form.querySelector('.goal-contribute-btn'),amount=parseGoalAmount(amountInput?.value),note=noteInput?.value.trim()||null,contributor=currentGoalContributor();
  if(!contributor){goalContributionStatus(form,'Ваш аккаунт не привязан к участнику семьи.','error');return}
  if(!(amount>0)){goalContributionStatus(form,'Введите сумму пополнения больше 0.','error');amountInput?.focus();return}
  form.dataset.saving='1';if(button){button.disabled=true;button.textContent='Сохраняем…'}goalContributionStatus(form,'Записываем в цель и расходы…','pending');
  try{
    const result=await saveLinkedGoalContribution(form.dataset.goal,amount,note);
    if(result?.error){goalContributionStatus(form,`Не удалось пополнить: ${result.error.message||String(result.error)}`,'error');return}
    if(!result?.data){goalContributionStatus(form,'Пополнение не сохранено. Повторите попытку.','error');return}
    if(typeof uiSound==='function')uiSound('success');
    amountInput.value='';if(noteInput)noteInput.value='';
    goalContributionStatus(form,`${money(amount)} внесено. Расход записан на ${contributor.display_name}.`,'success');
    renderStateChange();
  }catch(error){console.error('Ошибка пополнения цели',error);goalContributionStatus(form,`Не удалось пополнить: ${error?.message||String(error)}`,'error')}
  finally{form.dataset.saving='0';if(button){button.disabled=false;button.textContent='Пополнить'}}
}
function bindGoals(){
  const form=document.getElementById('goalForm');if(form)form.onsubmit=async e=>{e.preventDefault();const payload={family_id:state.family.id,name:document.getElementById('goalName').value.trim(),target_amount:Number(document.getElementById('goalTarget').value),target_date:document.getElementById('goalDate').value||null,note:document.getElementById('goalNote').value.trim()||null,created_by:state.user.id};const result=await saveGoalEntity('goal',null,payload);if(result.error)return notice('goalNotice',result.error.message||String(result.error));if(result.data)upsertById(state.goals,result.data);if(typeof uiSound==='function')uiSound('success');renderStateChange()};
  document.querySelectorAll('.goal-contribution-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();submitGoalContribution(f)});
  document.querySelectorAll('.goalWithdraw').forEach(b=>b.onclick=async()=>{const value=parseGoalAmount(prompt('Сколько вернуть из цели в доступный баланс?','0'));if(!value||value<0)return;const result=await saveLinkedGoalContribution(b.dataset.id,-value,'Возврат из накоплений');if(result.error)return alert(result.error.message||result.error);if(typeof uiSound==='function')uiSound('success');renderStateChange()});
  document.querySelectorAll('.goalArchive').forEach(b=>b.onclick=()=>setGoalArchived(b.dataset.id,true));document.querySelectorAll('.goalRestore').forEach(b=>b.onclick=()=>setGoalArchived(b.dataset.id,false));
  document.querySelectorAll('.goalDelete').forEach(b=>b.onclick=async()=>{if(!confirm('Удалить цель и историю её пополнений? Операции в журнале сохранятся как часть финансовой истории.'))return;const id=b.dataset.id,result=window.FinanceOffline?.deleteEntity?await window.FinanceOffline.deleteEntity('goal',id):await sb.from('financial_goals').delete().eq('id',id);if(result.error)return alert(result.error.message||result.error);state.goals=state.goals.filter(x=>x.id!==id);state.goalContributions=state.goalContributions.filter(x=>x.goal_id!==id);renderStateChange()});
}
async function setGoalArchived(id,archived){const result=await saveGoalEntity('goal',id,{archived});if(result.error)return alert(result.error.message||result.error);if(result.data)upsertById(state.goals,result.data);renderStateChange()}
