// Страница регулярных платежей: периодичность, дата, напоминания и статусы.
function recurringFrequencyLabel(value){return value==='weekly'?'Еженедельно':value==='yearly'?'Ежегодно':'Ежемесячно'}
recurringRow=function(r){
  const info=phase3DueDate(r),due=info?phase3DueText(info):'';
  return `<div class="recurring-row recurring-row-v3 ${phase3DueClass(info)}"><div><div class="recurring-title"><b>${esc(r.description||catName(r.category_id))}${r._offline?'<span class="offline-row-badge">Ожидает синхронизации</span>':''}</b>${r.active&&info?`<span class="due-chip ${phase3DueClass(info)}">${due}</span>`:''}</div><div class="muted" style="font-size:12px">${esc(personName(r.person_id))} · ${r.type==='expense'?'Расход':'Доход'} · ${recurringFrequencyLabel(r.frequency)} · ${info?info.date.toLocaleDateString('ru-RU'):'дата не задана'} · ${esc(catName(r.category_id))}</div></div><b class="${r.type==='expense'?'negative':'positive'}">${money(r.amount)}</b><div class="tx-actions"><span class="status-chip ${r.active?'on':'off'}">${r.active?'Активен':'Пауза'}</span><button class="btn btn-soft btn-small postRecurring" data-id="${r.id}">Оплачено</button><button class="icon-btn toggleRecurring" data-id="${r.id}" title="${r.active?'Поставить на паузу':'Возобновить'}">${r.active?'Ⅱ':'▶'}</button><button class="icon-btn deleteRecurring" data-id="${r.id}" title="Удалить">×</button></div></div>`;
};

recurringPage=function(){
  const expenseCats=state.categories.filter(c=>c.type==='expense');
  const alerts=phase3Upcoming();
  const today=phase3DateValue(new Date());
  return `<div class="page-head"><div><h2 class="page-title">Регулярные платежи</h2><div class="page-subtitle">У каждого платежа своя периодичность, ближайшая дата и срок напоминания.</div></div>${alerts.length?`<div class="reminder-summary"><b>${alerts.length}</b><span>требуют внимания</span></div>`:''}</div><div class="grid analytics-grid"><div class="card"><h3>Новый регулярный платёж</h3><div id="recNotice"></div><form id="recForm" class="quick-form"><div class="full segmented"><button type="button" data-rtype="expense" class="active">Расход</button><button type="button" data-rtype="income">Доход</button></div><div class="field"><label>Кто</label><select id="recPerson">${state.people.map(p=>`<option value="${p.id}">${esc(p.display_name)}</option>`).join('')}</select></div><div class="field"><label>Сумма, ₸</label><input id="recAmount" type="number" min="1" required></div><div class="field"><label>Периодичность</label><select id="recFrequency"><option value="weekly">Еженедельно</option><option value="monthly" selected>Ежемесячно</option><option value="yearly">Ежегодно</option></select></div><div class="field"><label>Следующий платёж</label><input id="recNextDate" type="date" value="${today}" required></div><div class="field"><label>Предупредить за, дней</label><input id="recReminderDays" type="number" min="0" max="60" value="3" required></div><div class="field"><label>Категория</label><select id="recCategory">${expenseCats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field full"><label>Комментарий</label><input id="recDescription" placeholder="Например: Интернет"></div><div class="full"><button class="btn btn-primary btn-wide">Добавить регулярный платёж</button></div></form></div><div class="card"><h3>Напоминания</h3>${alerts.length?alerts.map(({r,info})=>`<div class="reminder-card ${phase3DueClass(info)}"><span>${phase3DueText(info)}</span><b>${esc(r.description||catName(r.category_id))}</b><small>${money(r.amount)} · ${esc(personName(r.person_id))} · ${recurringFrequencyLabel(r.frequency)}</small></div>`).join(''):`<div class="empty compact-empty">Платежей, требующих внимания, сейчас нет</div>`}</div></div><div class="card" style="margin-top:15px"><h3>Список</h3>${state.recurring.length?state.recurring.map(r=>recurringRow(r)).join(''):'<div class="empty">Регулярных платежей пока нет</div>'}</div>`;
};
