// Действия регулярных платежей без полной перезагрузки семейной базы.
function recurringNextDate(r){const base=phase3LocalDate(r.next_due_date)||new Date(),d=new Date(base.getFullYear(),base.getMonth(),base.getDate());if(r.frequency==='weekly'){d.setDate(d.getDate()+7);return d}if(r.frequency==='yearly'){const month=d.getMonth(),day=d.getDate(),year=d.getFullYear()+1,last=new Date(year,month+1,0).getDate();return new Date(year,month,Math.min(day,last))}const targetMonth=d.getMonth()+1,targetYear=d.getFullYear()+Math.floor(targetMonth/12),month=((targetMonth%12)+12)%12,preferred=Number(r.day_of_month)||d.getDate(),last=new Date(targetYear,month+1,0).getDate();return new Date(targetYear,month,Math.min(preferred,last))}
function bindRecurring(){
  let recType='expense';const form=document.getElementById('recForm');if(!form)return;
  form.querySelectorAll('[data-rtype]').forEach(b=>b.onclick=()=>{recType=b.dataset.rtype;form.querySelectorAll('[data-rtype]').forEach(x=>x.classList.toggle('active',x===b));const cats=state.categories.filter(c=>c.type===recType);form.querySelector('#recCategory').innerHTML=cats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(typeof uiSound==='function')uiSound('switch')});
  form.onsubmit=async e=>{e.preventDefault();const nextDate=form.querySelector('#recNextDate').value,parsed=phase3LocalDate(nextDate),payload={family_id:state.family.id,person_id:form.querySelector('#recPerson').value,type:recType,amount:Number(form.querySelector('#recAmount').value),category_id:form.querySelector('#recCategory').value,subcategory_id:null,description:form.querySelector('#recDescription').value.trim()||null,day_of_month:parsed?.getDate()||1,frequency:form.querySelector('#recFrequency').value,next_due_date:nextDate,reminder_days:Number(form.querySelector('#recReminderDays').value||0),active:true,created_by:state.user.id};const {data,error}=await sb.from('recurring_payments').insert(payload).select().single();if(error)return notice('recNotice',error.message);upsertById(state.recurring,data);if(typeof uiSound==='function')uiSound('success');renderStateChange()};
  document.querySelectorAll('.toggleRecurring').forEach(b=>b.onclick=async()=>{const r=byId(state.recurring,b.dataset.id);const {data,error}=await sb.from('recurring_payments').update({active:!r.active}).eq('id',r.id).select().single();if(error)return alert(error.message);upsertById(state.recurring,data);if(typeof uiSound==='function')uiSound('switch');renderStateChange()});
  document.querySelectorAll('.deleteRecurring').forEach(b=>b.onclick=async()=>{if(!confirm('Удалить регулярный платёж?'))return;const id=b.dataset.id,{error}=await sb.from('recurring_payments').delete().eq('id',id);if(error)return alert(error.message);state.recurring=state.recurring.filter(x=>x.id!==id);if(typeof uiSound==='function')uiSound('delete');renderStateChange()});
  document.querySelectorAll('.postRecurring').forEach(b=>b.onclick=()=>postRecurring(b.dataset.id));
}
async function postRecurring(id){
  const r=byId(state.recurring,id);if(!r)return;const now=new Date();
  const {data,error}=await sb.rpc('create_family_transaction',{p_family_id:state.family.id,p_person_id:r.person_id,p_type:r.type,p_amount:Number(r.amount),p_category_id:r.category_id,p_subcategory_id:r.subcategory_id,p_description:r.description,p_occurred_at:now.toISOString()});if(error)return alert(error.message);const tx=Array.isArray(data)?data[0]:data;if(tx)syncTransactionState(tx);
  const next=recurringNextDate(r);const {data:updated,error:updateError}=await sb.from('recurring_payments').update({next_due_date:phase3DateValue(next),last_paid_at:now.toISOString(),last_generated_month:phase3MonthKey(now)}).eq('id',r.id).select().single();if(updateError)return alert(updateError.message);upsertById(state.recurring,updated);if(typeof uiSound==='function')uiSound('success');renderStateChange();
}
