// Действия регулярных платежей с офлайн-очередью.
function recurringNextDate(r){const base=phase3LocalDate(r.next_due_date)||new Date(),d=new Date(base.getFullYear(),base.getMonth(),base.getDate());if(r.frequency==='weekly'){d.setDate(d.getDate()+7);return d}if(r.frequency==='yearly'){const month=d.getMonth(),day=d.getDate(),year=d.getFullYear()+1,last=new Date(year,month+1,0).getDate();return new Date(year,month,Math.min(day,last))}const targetMonth=d.getMonth()+1,targetYear=d.getFullYear()+Math.floor(targetMonth/12),month=((targetMonth%12)+12)%12,preferred=Number(r.day_of_month)||d.getDate(),last=new Date(targetYear,month+1,0).getDate();return new Date(targetYear,month,Math.min(preferred,last))}
async function saveRecurringEntity(id,payload){if(window.FinanceOffline?.saveEntity)return window.FinanceOffline.saveEntity('recurring',{id:id||null,payload});if(id)return sb.from('recurring_payments').update(payload).eq('id',id).select().single();return sb.from('recurring_payments').insert(payload).select().single()}
function bindRecurring(){
  const form=document.getElementById('recForm');if(!form)return;
  form.onsubmit=async e=>{e.preventDefault();const nextDate=form.querySelector('#recNextDate').value,parsed=phase3LocalDate(nextDate),payload={family_id:state.family.id,person_id:form.querySelector('#recPerson').value,type:'expense',amount:Number(form.querySelector('#recAmount').value),category_id:form.querySelector('#recCategory').value,subcategory_id:null,description:form.querySelector('#recDescription').value.trim()||null,day_of_month:parsed?.getDate()||1,frequency:form.querySelector('#recFrequency').value,next_due_date:nextDate,reminder_days:Number(form.querySelector('#recReminderDays').value||0),active:true,created_by:state.user.id};const result=await saveRecurringEntity(null,payload);if(result.error)return notice('recNotice',result.error.message||String(result.error));if(result.data)upsertById(state.recurring,result.data);if(typeof uiSound==='function')uiSound('success');renderStateChange()};
  document.querySelectorAll('.toggleRecurring').forEach(b=>b.onclick=async()=>{const r=byId(state.recurring,b.dataset.id);const result=await saveRecurringEntity(r.id,{active:!r.active});if(result.error)return alert(result.error.message||result.error);if(result.data)upsertById(state.recurring,result.data);if(typeof uiSound==='function')uiSound('switch');renderStateChange()});
  document.querySelectorAll('.deleteRecurring').forEach(b=>b.onclick=async()=>{if(!confirm('Удалить регулярный платёж?'))return;const id=b.dataset.id,result=window.FinanceOffline?.deleteEntity?await window.FinanceOffline.deleteEntity('recurring',id):await sb.from('recurring_payments').delete().eq('id',id);if(result.error)return alert(result.error.message||result.error);state.recurring=state.recurring.filter(x=>x.id!==id);if(typeof uiSound==='function')uiSound('delete');renderStateChange()});
  document.querySelectorAll('.postRecurring').forEach(b=>b.onclick=()=>postRecurring(b.dataset.id));
}
async function postRecurring(id){
  const r=byId(state.recurring,id);if(!r)return;const now=new Date(),payload={person_id:r.person_id,type:r.type,amount:Number(r.amount),category_id:r.category_id,subcategory_id:r.subcategory_id||null,description:r.description||null,occurred_at:now.toISOString()},createArgs={p_family_id:state.family.id,p_person_id:r.person_id,p_type:r.type,p_amount:Number(r.amount),p_category_id:r.category_id,p_subcategory_id:r.subcategory_id||null,p_description:r.description||null,p_occurred_at:now.toISOString()};
  const result=window.FinanceOffline?.saveTransaction?await window.FinanceOffline.saveTransaction({payload,createArgs}):await sb.rpc('create_family_transaction',createArgs);if(result.error)return alert(result.error.message||result.error);const tx=Array.isArray(result.data)?result.data[0]:result.data;if(tx)syncTransactionState(tx);
  const next=recurringNextDate(r),recResult=await saveRecurringEntity(r.id,{next_due_date:phase3DateValue(next),last_paid_at:now.toISOString(),last_generated_month:phase3MonthKey(now)});if(recResult.error)return alert(recResult.error.message||recResult.error);if(recResult.data)upsertById(state.recurring,recResult.data);if(typeof uiSound==='function')uiSound('success');renderStateChange();
}
