// Refactored from phase3.js: transaction entry UX and preference memory.
let phase3Prefs={};
try{phase3Prefs=JSON.parse(localStorage.getItem('finance.phase3.prefs')||'{}')}catch(_){phase3Prefs={}}

function phase3QuickPairs(type,personId){const seen=new Set(),rows=[];for(const tx of state.transactions){if(tx.type!==type||tx.person_id!==personId)continue;const key=`${tx.category_id}:${tx.subcategory_id||''}`;if(seen.has(key))continue;seen.add(key);rows.push(tx);if(rows.length>=4)break}return rows}

transactionForm=function(tx=null){const type=tx?.type||state.txType,person=tx?.person_id||state.selectedPersonId;const pref=phase3Prefs?.[person]?.[type]||{};const cats=state.categories.filter(c=>c.type===type);let catId=tx?.category_id||pref.category_id||cats[0]?.id;if(!cats.some(c=>c.id===catId))catId=cats[0]?.id;const subs=state.subcategories.filter(s=>s.category_id===catId);let subId=tx?.subcategory_id||pref.subcategory_id||subs[0]?.id;if(!subs.some(s=>s.id===subId))subId=subs[0]?.id;const quick=phase3QuickPairs(type,person);return `<form id="txForm" class="quick-form quick-form-v3"><div class="full segmented"><button type="button" data-type="expense" class="${type==='expense'?'active':''}">Расход</button><button type="button" data-type="income" class="${type==='income'?'active':''}">Доход</button></div><div class="field full amount-field"><label>Сумма, ₸</label><input class="amount-input amount-hero" id="amount" type="number" min="1" step="1" inputmode="decimal" value="${tx?Number(tx.amount):''}" placeholder="0" required autofocus></div><div class="field full"><label>Кто</label>${personSwitch(person)}</div><input type="hidden" id="personId" value="${person||''}">${quick.length?`<div class="field full quick-pairs"><label>Недавние</label><div class="quick-pair-list">${quick.map(q=>`<button type="button" class="quick-pair" data-qcat="${q.category_id}" data-qsub="${q.subcategory_id||''}">${esc(catName(q.category_id))}${q.subcategory_id?` · ${esc(subName(q.subcategory_id))}`:''}</button>`).join('')}</div></div>`:''}<div class="field"><label>Категория</label><select id="categoryId">${cats.map(c=>`<option value="${c.id}" ${c.id===catId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Подкатегория</label><select id="subcategoryId">${subs.map(s=>`<option value="${s.id}" ${s.id===subId?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field full"><label>Комментарий</label><input id="description" value="${esc(tx?.description||'')}" placeholder="Необязательно"></div><details class="time-details full" ${tx?'open':''}><summary><span>Дата и время</span><b>${tx?'Изменить':'Сейчас'}</b></summary><div class="field"><input id="occurredAt" type="datetime-local" value="${localDT(tx?.occurred_at)}" required></div></details><div class="full"><button class="btn btn-primary btn-wide save-operation">${tx?'Сохранить изменения':'Сохранить операцию'}</button></div></form>`}

const refactorOriginalBindTransactionForm=bindTransactionForm;
bindTransactionForm=function(editId=null){refactorOriginalBindTransactionForm(editId);const form=document.getElementById('txForm');if(!form)return;document.querySelectorAll('.quick-pair').forEach(b=>b.onclick=()=>{const cat=document.getElementById('categoryId');cat.value=b.dataset.qcat;cat.dispatchEvent(new Event('change'));requestAnimationFrame(()=>{const sub=document.getElementById('subcategoryId');if(sub&&b.dataset.qsub)sub.value=b.dataset.qsub})});form.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.tagName!=='TEXTAREA'&&e.target.tagName!=='BUTTON'){e.preventDefault();form.requestSubmit()}})}

saveTransaction=async function(e,editId=null){e.preventDefault();notice(editId?'editNotice':'txNotice','');const personId=document.getElementById('personId').value;const type=document.getElementById('txType')?.value||state.txType;const categoryId=document.getElementById('categoryId').value;const subcategoryId=document.getElementById('subcategoryId').value||null;const payload={family_id:state.family.id,person_id:personId,type,amount:Number(document.getElementById('amount').value),category_id:categoryId,subcategory_id:subcategoryId,description:document.getElementById('description').value.trim()||null,occurred_at:new Date(document.getElementById('occurredAt').value).toISOString(),created_by:state.user.id,updated_at:new Date().toISOString()};const result=editId?await sb.from('transactions').update(payload).eq('id',editId):await sb.from('transactions').insert(payload);if(result.error)return notice(editId?'editNotice':'txNotice',result.error.message);if(!editId){phase3Prefs[personId]=phase3Prefs[personId]||{};phase3Prefs[personId][type]={category_id:categoryId,subcategory_id:subcategoryId};try{localStorage.setItem('finance.phase3.prefs',JSON.stringify(phase3Prefs))}catch(_){}}closeModal();await loadData()}
