// Phase 3 UX: faster daily entry, compact overview and recurring payment reminders.
const PHASE3_DAY_MS=86400000;
let phase3Prefs={};
try{phase3Prefs=JSON.parse(localStorage.getItem('finance.phase3.prefs')||'{}')}catch(_){phase3Prefs={}}

function phase3MonthKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function phase3DueDate(r,base=new Date()){
  if(!r?.active)return null;
  const today=new Date(base.getFullYear(),base.getMonth(),base.getDate());
  const make=(year,month)=>{const last=new Date(year,month+1,0).getDate();return new Date(year,month,Math.min(Number(r.day_of_month)||1,last))};
  let due=make(today.getFullYear(),today.getMonth());
  if(due<today||r.last_generated_month===phase3MonthKey(due))due=make(today.getFullYear(),today.getMonth()+1);
  const days=Math.round((due-today)/PHASE3_DAY_MS);
  return{date:due,days,key:phase3MonthKey(due)}
}
function phase3DueText(info){if(!info)return'';if(info.days===0)return'Сегодня';if(info.days===1)return'Завтра';if(info.days<=4)return`Через ${info.days} дня`;return`Через ${info.days} дней`}
function phase3DueClass(info){if(!info)return'';if(info.days===0)return'due-today';if(info.days<=3)return'due-soon';return''}
function phase3Upcoming(maxDays=3){return state.recurring.filter(r=>r.active).map(r=>({r,info:phase3DueDate(r)})).filter(x=>x.info&&x.info.days>=0&&x.info.days<=maxDays).sort((a,b)=>a.info.days-b.info.days)}
function phase3UpcomingAll(maxDays=14){return state.recurring.filter(r=>r.active).map(r=>({r,info:phase3DueDate(r)})).filter(x=>x.info&&x.info.days>=0&&x.info.days<=maxDays).sort((a,b)=>a.info.days-b.info.days)}

shell=function(content){return `<div class="app-shell"><aside class="sidebar"><div class="side-brand"><div class="brand"><div class="brand-badge">₸</div><span class="brand-text">Казна</span></div></div><nav class="side-nav">${nav('overview','⌂','Обзор')}${nav('operations','☷','Операции')}${nav('analytics','⌁','Аналитика')}${nav('budgets','◎','Бюджеты')}${nav('recurring','↻','Регулярные')}${nav('categories','▦','Категории')}</nav><div class="side-footer"><div class="side-copy"><b>${esc(state.family.name)}</b><div>Данные в Supabase</div></div></div></aside><main class="main">${header()}${content}</main></div>`}

nav=function(view,icon,label){const due=view==='recurring'?phase3Upcoming(3):[];const alert=due.length>0;return `<div class="nav-item ${state.view===view?'active':''} ${alert?'payment-alert':''}" data-view="${view}"><span class="nav-icon">${icon}</span><span class="nav-label">${label}</span>${alert?`<span class="nav-badge" title="Платежи в ближайшие 3 дня">${due.length}</span>`:''}</div>`}

function phase3BudgetPreview(){const current=state.budgets.filter(b=>b.year===+state.year&&b.month===+state.month);if(!current.length)return `<div class="empty compact-empty">Лимиты пока не заданы</div>`;return current.map(b=>{const spent=periodTx().filter(x=>x.type==='expense'&&x.category_id===b.category_id).reduce((a,x)=>a+Number(x.amount),0);const limit=Number(b.limit_amount)||0;const pct=limit?Math.round(spent/limit*100):0;return{b,spent,limit,pct}}).sort((a,b)=>b.pct-a.pct).slice(0,4).map(x=>`<div class="mini-budget"><div class="mini-budget-head"><span>${esc(catName(x.b.category_id))}</span><b class="${x.pct>100?'negative':x.pct>=80?'warning-text':''}">${x.pct}%</b></div><div class="budget-progress"><div class="budget-fill ${x.pct>100?'over':''}" style="width:${Math.min(100,x.pct)}%"></div></div><small>${money(x.spent)} из ${money(x.limit)}</small></div>`).join('')}

function phase3UpcomingPreview(){const rows=phase3UpcomingAll(10).slice(0,4);if(!rows.length)return `<div class="empty compact-empty">В ближайшие 10 дней платежей нет</div>`;return rows.map(({r,info})=>`<div class="upcoming-row ${phase3DueClass(info)}"><div><b>${esc(r.description||catName(r.category_id))}</b><small>${esc(personName(r.person_id))} · ${info.date.toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})}</small></div><div class="upcoming-right"><b class="${r.type==='expense'?'negative':'positive'}">${money(r.amount)}</b><span>${phase3DueText(info)}</span></div></div>`).join('')}

function phase3PeopleStrip(){return `<div class="people-compact">${state.people.map(p=>{const s=stats(p.id);return `<div class="person-compact"><div class="person-compact-name"><span class="avatar small-avatar">${p.label==='husband'?'М':'Ж'}</span><div><b>${esc(p.display_name)}</b><small>${p.label==='husband'?'Муж':'Жена'}</small></div></div><div class="person-compact-stat"><span>Доход</span><b class="positive">${money(s.income)}</b></div><div class="person-compact-stat"><span>Расход</span><b class="negative">${money(s.expense)}</b></div><div class="person-compact-stat balance-stat"><span>Баланс</span><b class="${s.balance>=0?'positive':'negative'}">${money(s.balance)}</b></div></div>`}).join('')}</div>`}

overviewPage=function(){const s=stats();const saved=s.income?Math.max(0,Math.round(s.balance/s.income*100)):0;return `<section class="overview-v3"><div class="overview-entry card entry-card"><div class="entry-head"><div><h3>Добавить операцию</h3><p>Основное действие — сумма, человек и категория. Время уже выставлено автоматически.</p></div><span class="entry-shortcut">Enter — сохранить</span></div><div id="txNotice"></div>${transactionForm()}</div><div class="overview-summary"><div class="summary-kpis"><div class="summary-kpi primary"><span>Баланс семьи</span><b class="${s.balance>=0?'positive':'negative'}">${money(s.balance)}</b></div><div class="summary-kpi"><span>Доходы</span><b class="positive">${money(s.income)}</b></div><div class="summary-kpi"><span>Расходы</span><b class="negative">${money(s.expense)}</b></div><div class="summary-kpi"><span>Сбережено</span><b>${saved}%</b></div></div><div class="card overview-last"><div class="entry-head"><div><h3>Последние операции</h3><p>${periodTx().length} записей за ${MONTHS[state.month-1].toLowerCase()}</p></div><button class="btn btn-soft btn-small" id="allOperations">Все операции</button></div>${transactionList(periodTx().slice(0,7),true)}</div><div class="overview-insights"><div class="card"><div class="entry-head"><div><h3>Бюджеты месяца</h3><p>Самые заполненные лимиты</p></div><button class="text-action" data-go="budgets">Открыть</button></div>${phase3BudgetPreview()}</div><div class="card"><div class="entry-head"><div><h3>Ближайшие платежи</h3><p>Регулярные обязательства</p></div><button class="text-action" data-go="recurring">Открыть</button></div>${phase3UpcomingPreview()}</div></div></div></section><section class="card people-strip-card"><div class="entry-head"><div><h3>Муж и жена</h3><p>Сводка за выбранный месяц</p></div></div>${phase3PeopleStrip()}</section>`}

function phase3QuickPairs(type,personId){const seen=new Set(),rows=[];for(const tx of state.transactions){if(tx.type!==type||tx.person_id!==personId)continue;const key=`${tx.category_id}:${tx.subcategory_id||''}`;if(seen.has(key))continue;seen.add(key);rows.push(tx);if(rows.length>=4)break}return rows}

transactionForm=function(tx=null){const type=tx?.type||state.txType,person=tx?.person_id||state.selectedPersonId;const pref=phase3Prefs?.[person]?.[type]||{};const cats=state.categories.filter(c=>c.type===type);let catId=tx?.category_id||pref.category_id||cats[0]?.id;if(!cats.some(c=>c.id===catId))catId=cats[0]?.id;const subs=state.subcategories.filter(s=>s.category_id===catId);let subId=tx?.subcategory_id||pref.subcategory_id||subs[0]?.id;if(!subs.some(s=>s.id===subId))subId=subs[0]?.id;const quick=phase3QuickPairs(type,person);return `<form id="txForm" class="quick-form quick-form-v3"><div class="full segmented"><button type="button" data-type="expense" class="${type==='expense'?'active':''}">Расход</button><button type="button" data-type="income" class="${type==='income'?'active':''}">Доход</button></div><div class="field full amount-field"><label>Сумма, ₸</label><input class="amount-input amount-hero" id="amount" type="number" min="1" step="1" inputmode="decimal" value="${tx?Number(tx.amount):''}" placeholder="0" required autofocus></div><div class="field full"><label>Кто</label>${personSwitch(person)}</div><input type="hidden" id="personId" value="${person||''}">${quick.length?`<div class="field full quick-pairs"><label>Недавние</label><div class="quick-pair-list">${quick.map(q=>`<button type="button" class="quick-pair" data-qcat="${q.category_id}" data-qsub="${q.subcategory_id||''}">${esc(catName(q.category_id))}${q.subcategory_id?` · ${esc(subName(q.subcategory_id))}`:''}</button>`).join('')}</div></div>`:''}<div class="field"><label>Категория</label><select id="categoryId">${cats.map(c=>`<option value="${c.id}" ${c.id===catId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Подкатегория</label><select id="subcategoryId">${subs.map(s=>`<option value="${s.id}" ${s.id===subId?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field full"><label>Комментарий</label><input id="description" value="${esc(tx?.description||'')}" placeholder="Необязательно"></div><details class="time-details full" ${tx?'open':''}><summary><span>Дата и время</span><b>${tx?'Изменить':'Сейчас'}</b></summary><div class="field"><input id="occurredAt" type="datetime-local" value="${localDT(tx?.occurred_at)}" required></div></details><div class="full"><button class="btn btn-primary btn-wide save-operation">${tx?'Сохранить изменения':'Сохранить операцию'}</button></div></form>`}

const phase3OriginalBindTransactionForm=bindTransactionForm;
bindTransactionForm=function(editId=null){phase3OriginalBindTransactionForm(editId);const form=document.getElementById('txForm');if(!form)return;document.querySelectorAll('.quick-pair').forEach(b=>b.onclick=()=>{const cat=document.getElementById('categoryId');cat.value=b.dataset.qcat;cat.dispatchEvent(new Event('change'));requestAnimationFrame(()=>{const sub=document.getElementById('subcategoryId');if(sub&&b.dataset.qsub)sub.value=b.dataset.qsub})});form.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.tagName!=='TEXTAREA'&&e.target.tagName!=='BUTTON'){e.preventDefault();form.requestSubmit()}})}

saveTransaction=async function(e,editId=null){e.preventDefault();notice(editId?'editNotice':'txNotice','');const personId=document.getElementById('personId').value;const type=document.getElementById('txType')?.value||state.txType;const categoryId=document.getElementById('categoryId').value;const subcategoryId=document.getElementById('subcategoryId').value||null;const payload={family_id:state.family.id,person_id:personId,type,amount:Number(document.getElementById('amount').value),category_id:categoryId,subcategory_id:subcategoryId,description:document.getElementById('description').value.trim()||null,occurred_at:new Date(document.getElementById('occurredAt').value).toISOString(),created_by:state.user.id,updated_at:new Date().toISOString()};const result=editId?await sb.from('transactions').update(payload).eq('id',editId):await sb.from('transactions').insert(payload);if(result.error)return notice(editId?'editNotice':'txNotice',result.error.message);if(!editId){phase3Prefs[personId]=phase3Prefs[personId]||{};phase3Prefs[personId][type]={category_id:categoryId,subcategory_id:subcategoryId};try{localStorage.setItem('finance.phase3.prefs',JSON.stringify(phase3Prefs))}catch(_){}}closeModal();await loadData()}

const phase3OriginalBindOverview=bindOverview;
bindOverview=function(){phase3OriginalBindOverview();document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.view=b.dataset.go;renderApp()})}

recurringRow=function(r){const info=phase3DueDate(r);const due=info?phase3DueText(info):'';return `<div class="recurring-row recurring-row-v3 ${phase3DueClass(info)}"><div><div class="recurring-title"><b>${esc(r.description||catName(r.category_id))}</b>${r.active&&info?`<span class="due-chip ${phase3DueClass(info)}">${due}</span>`:''}</div><div class="muted" style="font-size:12px">${esc(personName(r.person_id))} · ${r.type==='expense'?'Расход':'Доход'} · ${r.day_of_month} числа · ${esc(catName(r.category_id))}</div></div><b class="${r.type==='expense'?'negative':'positive'}">${money(r.amount)}</b><div class="tx-actions"><span class="status-chip ${r.active?'on':'off'}">${r.active?'Активен':'Пауза'}</span><button class="btn btn-soft btn-small postRecurring" data-id="${r.id}">Внести сейчас</button><button class="icon-btn toggleRecurring" data-id="${r.id}">${r.active?'Ⅱ':'▶'}</button><button class="icon-btn deleteRecurring" data-id="${r.id}">×</button></div></div>`}

recurringPage=function(){const expenseCats=state.categories.filter(c=>c.type==='expense');const alerts=phase3Upcoming(3);return `<div class="page-head"><div><h2 class="page-title">Регулярные платежи</h2><div class="page-subtitle">Напоминание включается автоматически за 3 дня до ближайшей даты.</div></div>${alerts.length?`<div class="reminder-summary"><b>${alerts.length}</b><span>платеж${alerts.length===1?'':'а'} в ближайшие 3 дня</span></div>`:''}</div><div class="grid analytics-grid"><div class="card"><h3>Новый регулярный платёж</h3><div id="recNotice"></div><form id="recForm" class="quick-form"><div class="full segmented"><button type="button" data-rtype="expense" class="active">Расход</button><button type="button" data-rtype="income">Доход</button></div><div class="field"><label>Кто</label><select id="recPerson">${state.people.map(p=>`<option value="${p.id}">${esc(p.display_name)}</option>`).join('')}</select></div><div class="field"><label>Сумма, ₸</label><input id="recAmount" type="number" min="1" required></div><div class="field"><label>День месяца</label><input id="recDay" type="number" min="1" max="31" value="1" required></div><div class="field"><label>Категория</label><select id="recCategory">${expenseCats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field full"><label>Комментарий</label><input id="recDescription" placeholder="Например: Интернет"></div><div class="full"><button class="btn btn-primary btn-wide">Добавить регулярный платёж</button></div></form></div><div class="card"><h3>Напоминания</h3>${alerts.length?alerts.map(({r,info})=>`<div class="reminder-card ${phase3DueClass(info)}"><span>${phase3DueText(info)}</span><b>${esc(r.description||catName(r.category_id))}</b><small>${money(r.amount)} · ${esc(personName(r.person_id))}</small></div>`).join(''):`<div class="empty compact-empty">На ближайшие 3 дня ничего не запланировано</div>`}</div></div><div class="card" style="margin-top:15px"><h3>Список</h3>${state.recurring.length?state.recurring.map(r=>recurringRow(r)).join(''):'<div class="empty">Регулярных платежей пока нет</div>'}</div>`}
