// Core runtime: Supabase client, state, common helpers and data loading.
const SUPABASE_URL='https://llgubwtuhxpdpxaxxcft.supabase.co';
const SUPABASE_KEY='sb_publishable_xLCywB_jYDuPJrTKflv5LQ_r8weOhFb';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const app=document.getElementById('app');
const MONTHS=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
let state={user:null,family:null,people:[],categories:[],subcategories:[],transactions:[],budgets:[],recurring:[],view:'overview',txType:'expense',selectedPersonId:null,year:new Date().getFullYear(),month:new Date().getMonth()+1,filters:{person:'all',type:'all',category:'all'},charts:[]};

const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'KZT',maximumFractionDigits:0}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const byId=(arr,id)=>arr.find(x=>x.id===id);
const localDT=d=>{const x=d?new Date(d):new Date();const pad=n=>String(n).padStart(2,'0');return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}T${pad(x.getHours())}:${pad(x.getMinutes())}`};
function notice(id,msg,type='error'){const el=document.getElementById(id);if(el)el.innerHTML=msg?`<div class="notice ${type}">${esc(msg)}</div>`:''}
function periodTx(){return state.transactions.filter(x=>{const d=new Date(x.occurred_at);return d.getFullYear()===+state.year&&d.getMonth()+1===+state.month})}
function stats(personId){const tx=periodTx().filter(x=>!personId||x.person_id===personId);const income=tx.filter(x=>x.type==='income').reduce((a,b)=>a+Number(b.amount),0);const expense=tx.filter(x=>x.type==='expense').reduce((a,b)=>a+Number(b.amount),0);return{income,expense,balance:income-expense}}
function catName(id){return byId(state.categories,id)?.name||'Без категории'}
function subName(id){return byId(state.subcategories,id)?.name||''}
function personName(id){return byId(state.people,id)?.display_name||'Участник'}

async function bootstrap(){const {data:{session}}=await sb.auth.getSession();state.user=session?.user||null;if(!state.user)return renderAuth();await loadData()}

function renderAuth(signup=false){app.innerHTML=`<div class="auth-shell"><section class="auth-hero"><div class="brand"><div class="brand-badge">₸</div><span>Семейная казна</span></div><div><h1>Семейные деньги под вашим флагом.</h1><p>Доходы, расходы, бюджеты и регулярные платежи мужа и жены.</p></div><small style="color:#b7a88d">MG-Trener Finance · 2026</small></section><section class="auth-card-wrap"><div class="auth-card"><h2>${signup?'Создать аккаунт':'Вход в казну'}</h2><div id="authNotice"></div><form id="authForm"><div class="field"><label>Email</label><input id="email" type="email" required autocomplete="email"></div><div class="field"><label>Пароль</label><input id="password" type="password" required minlength="8" autocomplete="${signup?'new-password':'current-password'}"></div><button class="btn btn-primary btn-wide">${signup?'Создать аккаунт':'Войти'}</button></form></div></section></div>`}

async function loadData(){const {data:fu,error}=await sb.from('family_users').select('family_id,role,families(id,name,currency,created_by)').limit(1);if(error)return app.innerHTML=`<div class="boot">Ошибка: ${esc(error.message)}</div>`;if(!fu?.length)return renderOnboarding();state.family=fu[0].families;const [p,c,s,t,b,r]=await Promise.all([sb.from('people').select('*').eq('family_id',state.family.id).order('label'),sb.from('categories').select('*').or(`family_id.is.null,family_id.eq.${state.family.id}`).order('sort_order'),sb.from('subcategories').select('*').order('sort_order'),sb.from('transactions').select('*').eq('family_id',state.family.id).order('occurred_at',{ascending:false}).limit(1000),sb.from('budgets').select('*').eq('family_id',state.family.id),sb.from('recurring_payments').select('*').eq('family_id',state.family.id).order('day_of_month')]);state.people=p.data||[];state.categories=c.data||[];state.subcategories=s.data||[];state.transactions=t.data||[];state.budgets=b.data||[];state.recurring=r.data||[];if(!state.selectedPersonId&&state.people[0])state.selectedPersonId=state.people.find(x=>x.linked_user_id===state.user?.id)?.id||state.people[0].id;renderApp()}

function renderOnboarding(){app.innerHTML=`<div class="onboarding-shell"><div class="onboarding-card"><div class="brand" style="color:#3b2613;margin-bottom:22px"><div class="brand-badge">₸</div><span>Семейная казна</span></div><h2>Создадим вашу семью</h2><div id="onboardNotice"></div><form id="onboardForm"><div class="field"><label>Название семьи</label><input id="familyName" value="Наша семья" required></div><div class="field"><label>Имя мужа</label><input id="husbandName" value="Муж" required></div><div class="field"><label>Имя жены</label><input id="wifeName" value="Жена" required></div><div class="field"><label>Кто входит сейчас?</label><select id="who"><option value="husband">Муж</option><option value="wife">Жена</option></select></div><button class="btn btn-primary btn-wide">Создать семейную базу</button></form></div></div>`;document.getElementById('onboardForm').onsubmit=async e=>{e.preventDefault();const familyName=document.getElementById('familyName').value.trim(),husbandName=document.getElementById('husbandName').value.trim(),wifeName=document.getElementById('wifeName').value.trim(),who=document.getElementById('who').value;const {data:f,error:fe}=await sb.from('families').insert({name:familyName,created_by:state.user.id}).select().single();if(fe)return notice('onboardNotice',fe.message);const {error:fue}=await sb.from('family_users').insert({family_id:f.id,user_id:state.user.id,role:'owner'});if(fue)return notice('onboardNotice',fue.message);const {error:pe}=await sb.from('people').insert([{family_id:f.id,label:'husband',display_name:husbandName,linked_user_id:who==='husband'?state.user.id:null},{family_id:f.id,label:'wife',display_name:wifeName,linked_user_id:who==='wife'?state.user.id:null}]);if(pe)return notice('onboardNotice',pe.message);await sb.from('profiles').upsert({id:state.user.id,display_name:who==='husband'?husbandName:wifeName});await loadData()}}
function closeModal(){document.getElementById('modal')?.remove()}
